const ACTIONS = {
  TOGGLE_ADD_PRODUCT_MODAL: "TOGGLE_LOGIN_MODAL",
  TOGGLE_EDIT_PRODUCT_MODAL: "TOGGLE_EDIT_PRODUCT_MODAL",
  TOGGLE_MANAGE_CATEGORY_MODAL: "TOGGLE_MANAGE_CATEGORY_MODAL",
  TOGGLE_AUTH_MODAL: "TOGGLE_AUTH_MODAL",
  SET_SELECTED_PRODUCTED: "SET_SELECTED_PRODUCTED",
  SET_USER_INFO:"SET_USER_INFO",
  RESET: "RESET",
};

export default ACTIONS;
