const ACTIONS = {
  TOGGLE_ADD_PRODUCT_MODAL: "TOGGLE_LOGIN_MODAL",
  TOGGLE_EDIT_PRODUCT_MODAL: "TOGGLE_EDIT_PRODUCT_MODAL",
  SET_SELECTED_PRODUCTED: "SET_SELECTED_PRODUCTED",
  RESET:"RESET"
};

export default ACTIONS;
