export const products = [
    {
      productName: "Apple iPhone 12",
      price: 999,
      category: { value: 1, label: "Electronics" },
      availability: { value: "AVAILABLE", label: "Available" },
      availableSince: "2022-01-01",
    },
    {
      productName: "Samsung Galaxy S21",
      price: 899,
      category: { value: 1, label: "Electronics" },
      availability: { value: "DISCONTINUED", label: "Discontinued" },
      availableSince: "2022-02-15",
    },
    {
      productName: "Nike Air Max 90",
      price: 129,
      category: { value: 2, label: "Footwear" },
      availability: { value: "AVAILABLE", label: "Available" },
      availableSince: "2022-03-10",
    },
    {
      productName: "Sony PlayStation 5",
      price: 499,
      category: { value: 3, label: "Gaming" },
      availability: { value: "UNAVAILABLE", label: "Unavailable" },
      availableSince: "2022-04-20",
    },
    {
      productName: "Samsung QLED 4K TV",
      price: 149,
      category: { value: 1, label: "Electronics" },
      availability: { value: "AVAILABLE", label: "Available" },
      availableSince: "2022-05-05",
    },
    {
      productName: "Adidas Ultraboost",
      price: 169,
      category: { value: 2, label: "Footwear" },
      availability: { value: "DISCONTINUED", label: "Discontinued" },
      availableSince: "2022-06-15",
    },
    {
      productName: "Nintendo Switch",
      price: 299,
      category: { value: 3, label: "Gaming" },
      availability: { value: "AVAILABLE", label: "Available" },
      availableSince: "2022-07-10",
    },
    {
      productName: "Dell XPS 13",
      price: 129,
      category: { value: 1, label: "Electronics" },
      availability: { value: "AVAILABLE", label: "Available" },
      availableSince: "2022-08-25",
    },
    {
      productName: "Nike Air Jordan 1",
      price: 199,
      category: { value: 2, label: "Footwear" },
      availability: { value: "UNAVAILABLE", label: "Unavailable" },
      availableSince: "2022-09-17",
    },
    {
      productName: "PlayStation 5 DualSense Controller",
      price: 69,
      category: { value: 3, label: "Gaming" },
      availability: { value: "AVAILABLE", label: "Available" },
      availableSince: "2022-10-30",
    },
    // Add more objects as needed with different items
  ];